### ISSUE TITLE
Problemas ao executar a rede-cnpj

### ISSUE THREAD

**Issue by ndr3wpss** [rictom/rede-cnpj#9]
Olá, tudo bem? Espero que sim!
Primeiro de tudo gostaria de parabenizá-lo pelo projeto desenvolvido. Ademais, estou tendo problemas ao conectar a rede-cnpj pelo console. Após colocar o prompt do anaconda na pasta de redes e executar o comando ---> python rede.py, obtenho o texto abaixo como output:

(base) C:\Users\andrew.santos_freteb\Documents\rede-cnpj-master\rede>python rede.py
Carregando rede_sqlite_cnpj
Utilizando rede_sqlite_cnpj como rede_relacionamentos.
módulo rede_spacy não foi carregado:  No module named 'textract'
Traceback (most recent call last):
  File "C:\Users\andrew.santos_freteb\Documents\rede-cnpj-master\rede\rede.py", line 40, in <module>
    limiter = flask_limiter.Limiter(app, key_func=get_remote_address) #, default_limits=["200 per day", "50 per hour"])
TypeError: __init__() got multiple values for argument 'key_func'

Já instalei as supostas bibliotecas que faltam, tais como: textract, folium, aiohttp, entre outras... Já que após instalada, O module named '    '  muda, tornando um ciclo infinito... Se possível, gostaria de uma ajuda para resolver o impasse! 
Mt obg!!
Andrew.

**Comment by rictom** [comment]
Obrigado por relatar o problema.

Vc rodou o comando
pip install -r requirements.txt
??
Em teoria isso instalaria a maioria dos bibliotecas necessárias. 

Como está dando erro especificamente nessa linha 40, talvez seja alguma alteração na versão dessa biblioteca flask_limiter... A atual é 3.3, enquanto que eu estou usando 2.5.1. Eu testei aqui, de fato, se usar uma versão mais nova do flask_limiter dá esse erro que vc relatou. 

A solução é alterar a linha 40 do rede.py para 
limiter = flask_limiter.Limiter(app=app, key_func=get_remote_address)

Teste aí e me avisa se funciona.

**Comment by ACamilo26** [comment]
Olá rictom, não consigo acessar esse site https://www.redecnpj.com.br/ . A informação que aparece é "502 Bad Gateway". Há previsão de voltar a funcionar?

**Comment by rictom** [comment]
Olá, 
Depois de receber duas dezenas de pedidos de remoção de conteúdo, ainda que todas as informações na redecnpj sejam públicas, decidi suspender a consulta online. Você pode baixar o código aqui no github e executar localmente no seu computador. As orientações estão aqui: https://github.com/rictom/rede-cnpj/blob/master/doc/instalacao_windows.md

**Comment by jcrmarques** [comment]
não estou conseguindo abrir o arquivo no anaconda, aparece   a seguinte mensagem 
ERROR: Could not find a version that satisfies the requirement flask-limiter (from versions: none)
ERROR: No matching distribution found for flask-limiter
WARNING: There was an error checking the latest version of pip.

**Comment by rictom** [comment]
Cole o texto do console para ver o erro

**Comment by Nilsonmichiles** [comment]
Rictom! acompanho o seu trabalho há alguns anos! Uma pena! foi o primeiro contato com grafos na prática para muita gente. :(

**Comment by guisassi** [comment]
Por favor, grave uma video aula no YouTube. Preciso muito dessa ajuda. 
O seu trabalho é de suma importância.

**Comment by guisassi** [comment]
Eu me perdi na parte de usar a base completa de CNPJ poderia me explicar melhor?

**Comment by rictom** [comment]
Você está seguindo o tutorial https://github.com/rictom/rede-cnpj/blob/master/doc/instalacao_windows.md ? 
Primeiro seria bom saber se você conseguiu abrir a rede com a base de teste. Funcionou?

**Comment by rictom** [comment]
Você está seguindo o tutorial https://github.com/rictom/rede-cnpj/blob/master/doc/instalacao_windows.md ? 
Primeiro seria bom saber se você conseguiu abrir a rede com a base de teste. Funcionou?

**Comment by jcrmarques** [comment]
Prezado 
Bom dia!


               eu segui o passo a passo do site, baxei o anaconda, baixei os arquivos, porém ao executar no anaconda, apareceu a mensagem de erro que enviei no site.

 
 
 



De: "rictom" ***@***.***>
Enviada: 2023/05/17 07:44:05
Para: ***@***.***
Cc:  ***@***.***, ***@***.***
Assunto:  Re: [rictom/rede-cnpj] Problemas ao executar a rede-cnpj (Issue #9)
 

 

Você está seguindo o tutorial https://github.com/rictom/rede-cnpj/blob/master/doc/instalacao_windows.md ?
Primeiro seria bom saber se você conseguiu abrir a rede com a base de teste. Funcionou?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/rictom/rede-cnpj/issues/9#issuecomment-1551162042", "url": "https://github.com/rictom/rede-cnpj/issues/9#issuecomment-1551162042", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by rictom** [comment]
Isto aqui?
não estou conseguindo abrir o arquivo no anaconda, aparece a seguinte mensagem
ERROR: Could not find a version that satisfies the requirement flask-limiter (from versions: none)
ERROR: No matching distribution found for flask-limiter
WARNING: There was an error checking the latest version of pip.

Você precisa copiar o texto a PARTIR do comando que vc executou, senão não dá pra saber qual a operação que vc fez e em que ponto aconteceu o erro. Normalmente aparece o arquivo que deu o erro e a linha

**Comment by ACamilo26** [comment]
Olá, bom dia, rictom! Como vc informou que o sistema não está mais online na internet, fiz a instalação local e vou relatar minha experiencia de usuário. 1- Com relação a instalação do projeto no windows com o tutorial fornecido não tive dificuldade, bastou seguir os passos atentamente e conseguir rodar a versão teste. Tudo foi perfeito. 2- Com relação à base de dados CNPJ completa, tive dificuldade, o tutorial para obtenção e tratamento dessa base não é claro e foi necessário usar minha intuição para poder prosseguir. Talvez fosse interessante aclarar o tutorial. Consegui fazer todo o tratamento e gerar o arquivo CNPJ.db, e posteriormente, tive também dificuldade para gerar o arquivo rede.db, mas também consegui. O projeto funcionou com a base completa de dados. Fiz algumas pesquisas, e constatei que o projeto é notável, facilitando muito o trabalho de quem precisa de informações desse tipo.
Notei algumas inconsistências quando utilizei o sistema por isso vou lhe relatar o feedback:
Consultei um CNPJ que eu sabia q tinha outras 4 filiais, contudo automaticamente o sistema não informou, tive que inserir uma a uma as filiais. Não sei se isso é erro do sistema ou alguma falha minha mas talvez valha a pena investigar para aprimorar o projeto se o caso.
Consultei alguns CNPJs  (MEIs) automaticamente o sistema não forneceu o sócio nem deixou incluir, e sabendo do sócio desta empresa também era sócio de outra, não forneceu também a informação ligação, foi necessário pesquisar a outra empresa e esta sim, forneceu automaticamente a ligação com os sócios, mas não ligou à primeira empresa em questão. Não sei se isso é erro do sistema ou alguma falha minha mas talvez valha a pena investigar para aprimorar o projeto se o caso.
Se vc precisar dos CNPJs que consultei e sócios me  informe que lhe forneço para vc fazer os testes por ai.
Outra coisa que eu não consegui fazer é ligar um elemento em outro (CNPJ à CNPJ ou sócio) quando o sistema não o faz automaticamente, assim, pergunto se é possivel fazer essa ligação?
Vou continuar utilizando o projeto que realmente é maravilhoso e vou lhe dando o feedback.
Obrigado.

**Comment by jcrmarques** [comment]
PRezado
não estou conseguindo acessar, veja tela de erro
 
(base) C:\Users\jose.marques\Desktop\rede-cnpj-master>pip install -r requirements.txt
Requirement already satisfied: flask in c:\users\jose.marques\appdata\local\anaconda3\lib\site-packages (from -r requirements.txt (line 1)) (2.2.2)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'Foi forçado o cancelamento de uma conexão existente pelo host remoto', None, 10054, None))': /simple/flask-limiter/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'Foi forçado o cancelamento de uma conexão existente pelo host remoto', None, 10054, None))': /simple/flask-limiter/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'Foi forçado o cancelamento de uma conexão existente pelo host remoto', None, 10054, None))': /simple/flask-limiter/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'Foi forçado o cancelamento de uma conexão existente pelo host remoto', None, 10054, None))': /simple/flask-limiter/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'Foi forçado o cancelamento de uma conexão existente pelo host remoto', None, 10054, None))': /simple/flask-limiter/
ERROR: Could not find a version that satisfies the requirement flask-limiter (from versions: none)
ERROR: No matching distribution found for flask-limiter
WARNING: There was an error checking the latest version of pip.

(base) C:\Users\jose.marques\Desktop\rede-cnpj-master>
 



De: "ACamilo26" ***@***.***>
Enviada: 2023/05/17 09:48:56
Para: ***@***.***
Cc:  ***@***.***, ***@***.***
Assunto:  Re: [rictom/rede-cnpj] Problemas ao executar a rede-cnpj (Issue #9)
 

 

Olá, bom dia, rictom! Como vc informou que o sistema não está mais online na internet, fiz a instalação local e vou relatar minha experiencia de usuário. 1- Com relação a instalação do projeto no windows com o tutorial fornecido não tive dificuldade, bastou seguir os passos atentamente e conseguir rodar a versão teste. Tudo foi perfeito. 2- Com relação à base de dados CNPJ completa, tive dificuldade, o tutorial para obtenção e tratamento dessa base não é claro e foi necessário usar minha intuição para poder prosseguir. Talvez fosse interessante aclarar o tutorial. Consegui fazer todo o tratamento e gerar o arquivo CNPJ.db, e posteriormente, tive também dificuldade para gerar o arquivo rede.db, mas também consegui. O projeto funcionou com a base completa de dados. Fiz algumas pesquisas, e constatei que o p
 rojeto é notável, facilitando muito o trabalho de quem precisa de informações desse tipo.
Notei algumas inconsistências quando utilizei o sistema por isso vou lhe relatar o feedback:
Consultei um CNPJ que eu sabia q tinha outras 4 filiais, contudo automaticamente o sistema não informou, tive que inserir uma a uma as filiais. Não sei se isso é erro do sistema ou alguma falha minha mas talvez valha a pena investigar para aprimorar o projeto se o caso.
Consultei alguns CNPJs (MEIs) automaticamente o sistema não forneceu o sócio nem deixou incluir, e sabendo do sócio desta empresa também era sócio de outra, não forneceu também a informação ligação, foi necessário pesquisar a outra empresa e esta sim, forneceu automaticamente a ligação com os sócios, mas não ligou à primeira empresa em questão. Não sei se isso é erro do sistema ou alguma falha minha mas talvez valha a pena investigar para aprimorar o projeto se o caso.
Se vc precisar dos CNPJs que consultei e sócios me informe que lhe forneço para vc fazer os testes por ai.
Outra coisa que eu não consegui fazer é ligar um elemento em outro (CNPJ à CNPJ ou sócio) quando o sistema não o faz automaticamente, assim, pergunto se é possivel fazer essa ligação?
Vou continuar utilizando o projeto que realmente é maravilhoso e vou lhe dando o feedback.
Obrigado.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/rictom/rede-cnpj/issues/9#issuecomment-1551331689", "url": "https://github.com/rictom/rede-cnpj/issues/9#issuecomment-1551331689", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by rictom** [comment]
Olá @ACamilo26,

Legal que vc conseguiu gerar as tabelas e rodar o projeto. 
a) De fato, essa questão das filiais é um erro que percebi semana passada, se a filial não tem nome fantasia não está aparecendo na busca "RADICALCNPJ"@N
Se vc tiver paciência pra rodar o script rede_cria_tabela.py de novo, vc 
altera as linhas 122 de
select 'PJ_' || te.cnpj ||'-' || te.nome_fantasia  as id_descricao 
from cnpj.estabelecimento te 
where trim(te.nome_fantasia) <>''

para 

select 'PJ_' || te.cnpj ||'-' || te.nome_fantasia  as id_descricao 
from cnpj.estabelecimento te 

Isto é, removendo o where. Isto deve resolver esse problema de não achar as filiais.

b) Realmente como o MEI não tem o sócio na tabela de sócios, vai aparecer como um item isolado no gráfico. Seria uma possibilidade pra estudar, mas  não é sempre que a Razão Social de MEI = NOME + CPF, acho que tem um novo padrão COMEÇO DO CNPJ + NOME

c) Para ligar dois itens, vc primeiro seleciona os dois itens. Pra selecionar, vc clica no primeiro item, aperte a tecla SHIFT e depois clica no segundo. Assim vc tem os dois itens selecionados. Depois aperta a tecla L, que vai aparecer um inputbox pra você inserir o nome da ligação.

Se vc puder informar quanto tempo levou para rodar esses scripts, seria de ajuda pra montar uma estatística disso.

> Olá, bom dia, rictom! Como vc informou que o sistema não está mais online na internet, fiz a instalação local e vou relatar minha experiencia de usuário. 1- Com relação a instalação do projeto no windows com o tutorial fornecido não tive dificuldade, bastou seguir os passos atentamente e conseguir rodar a versão teste. Tudo foi perfeito. 2- Com relação à base de dados CNPJ completa, tive dificuldade, o tutorial para obtenção e tratamento dessa base não é claro e foi necessário usar minha intuição para poder prosseguir. Talvez fosse interessante aclarar o tutorial. Consegui fazer todo o tratamento e gerar o arquivo CNPJ.db, e posteriormente, tive também dificuldade para gerar o arquivo rede.db, mas também consegui. O projeto funcionou com a base completa de dados. Fiz algumas pesquisas, e constatei que o projeto é notável, facilitando muito o trabalho de quem precisa de informações desse tipo. Notei algumas inconsistências quando utilizei o sistema por isso vou lhe relatar o feedback: Consultei um CNPJ que eu sabia q tinha outras 4 filiais, contudo automaticamente o sistema não informou, tive que inserir uma a uma as filiais. Não sei se isso é erro do sistema ou alguma falha minha mas talvez valha a pena investigar para aprimorar o projeto se o caso. Consultei alguns CNPJs (MEIs) automaticamente o sistema não forneceu o sócio nem deixou incluir, e sabendo do sócio desta empresa também era sócio de outra, não forneceu também a informação ligação, foi necessário pesquisar a outra empresa e esta sim, forneceu automaticamente a ligação com os sócios, mas não ligou à primeira empresa em questão. Não sei se isso é erro do sistema ou alguma falha minha mas talvez valha a pena investigar para aprimorar o projeto se o caso. Se vc precisar dos CNPJs que consultei e sócios me informe que lhe forneço para vc fazer os testes por ai. Outra coisa que eu não consegui fazer é ligar um elemento em outro (CNPJ à CNPJ ou sócio) quando o sistema não o faz automaticamente, assim, pergunto se é possivel fazer essa ligação? Vou continuar utilizando o projeto que realmente é maravilhoso e vou lhe dando o feedback. Obrigado.

**Comment by guisassi** [comment]
Ao invés de suspender o serviço, já pensou em cobrar uma mensalidade? Deste modo não seriam todos que teriam acesso, bem como os que precisam da ferramenta não ficariam sem.

**Comment by rictom** [comment]
Acho que a cobrança traria outros problemas. Eu fiz um aplicativo em Windows para a RedeCNPJ. Dê uma olhada na página https://www.redecnpj.com.br/rede/

**Comment by rictom** [comment]
qual o tamanho do arquivo cnpj.db? Parece que não concluiu a tarefa, porque não achou a tabela de sócios

**Comment by Dr4coder** [comment]
> 

O tamanho ficou em 18. Provavelmente seja isso. Vou refazer o banco de dados e reporto o resultado.

**Comment by Mercadante79** [comment]
Boa tarde,

Também não estou conseguindo rodar. Já refiz o processo várias vezes sem sucesso, inclusive já baixei os arquivos mais de uma vez achando que pudesse estar corrompido.

Quando rodo o processo de dados_cnpj_para_sqlite.py ele da o seguinte aviso

carregando tabela dados-publicos\F.K03200$Z.D30513.CNAECSV
C:\cnpj-sqlite-main\dados_cnpj_para_sqlite.py:48: RemovedIn20Warning: ←[31mDeprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. ←[32mTo prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". ←[36mSet environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message.←[0m (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  engine.execute(f'CREATE INDEX idx_{nomeTabela} ON {nomeTabela}(codigo);')

Mas prossegue com a criação dos arquivos.

O meu arquivo cnpj.db depois de finalizado todo o processo fica com 18.569.708KB
Quanto tento gerar o arquivo rede.db o python me retorna o seguinte erro:

C:\rede-cnpj-master\rede\bases>py rede_cria_tabela_rede.db.py
Este script vai criar ou alterar a base rede.db. Leva cerca de 1 hora. Deseja prosseguir (y,n)?y
Wed Jun 14 17:07:58 2023 Inicio - criando tabela rede.db
------------------------------
Wed Jun 14 17:07:58 2023 -executando parte: 1/14

-- cria tabela de ligação (necessário a partir de versão 0.8.9 (outubro/2022)
drop table if exists ligacao

------------------------------
Wed Jun 14 17:07:58 2023 -executando parte: 2/14

drop table if exists ligacao1

------------------------------
Wed Jun 14 17:07:58 2023 -executando parte: 3/14

-- PJ->PJ vinculo sócio pessoa juridica
create table ligacao1 AS
select  'PJ_'||t.cnpj_cpf_socio as origem, 'PJ_'||t.cnpj as destino, sq.descricao as tipo, 'socios' as base
from cnpj.socios t
left join cnpj.qualificacao_socio sq ON sq.codigo=t.qualificacao_socio
where length(t.cnpj_cpf_socio)=14 --t.nome_socio=''

Traceback (most recent call last):
  File "C:\rede-cnpj-master\rede\bases\rede_cria_tabela_rede.db.py", line 138, in <module>
    executaSequencia(camDBrede, sqlsequencia=sql_ligacao)
  File "C:\rede-cnpj-master\rede\bases\rede_cria_tabela_rede.db.py", line 123, in executaSequencia
    engine.execute(sql)
sqlite3.OperationalError: no such table: cnpj.socios

Consegue me orientar com o caminho das pedras?

Obrigado.

Att.

**Comment by rictom** [comment]
O arquivo cnpj.db tem quantos registros? Se vc abrir esse arquivo no dbBrowser, tem que aparecer estas tabelas: 
![image](https://github.com/rictom/rede-cnpj/assets/71139693/098931c8-4915-4713-a65c-58c670e2b2db)

![image](https://github.com/rictom/rede-cnpj/assets/71139693/699abf6d-f0c1-437a-818d-49deb84a0273)

**Comment by Mercadante79** [comment]
Ele não criou todas as tabelas, falta _referencia, sócios.
Vi que no script ele tenta dropar a tabela socios_original, mas tb da erro no comando DROP.
![image](https://github.com/rictom/rede-cnpj/assets/65542760/edfec14c-1efe-4230-b904-7f77e2ecad19)

Se eu navegar na socios_original, ela esta vazia.

![image](https://github.com/rictom/rede-cnpj/assets/65542760/29c35931-baa8-4dbd-bb7c-dbcf88540efb)

**Comment by Mercadante79** [comment]
Boa tarde!

Ele não estava criando todas as tabelas por falta de memoria em minha maquina. Assim que resolvi esse problema funcionou perfeitamente seguindo o passo a passo.

Obrigado e parabéns pelo projeto.
